#! /bin/sh

today=$(date '+%A, %d %b %Y')

export TERM=xterm
cal --color=always \
    | sed 's/\x1b\[[7;]*m/\<b\>\<u\>/g' \
    | sed 's/\x1b\[[27;]*m/\<\/u\>\<\/b\>/g' \
    | rofi -dmenu -p "$today" \
        -markup-rows -no-fullscreen -hide-scrollbar -lines 7 \
	-font 'Terminus bold 12' \
	-theme "$HOME/.config/rofi/themes/green-grey-blue-theme.rasi" \
        -theme-str '#inputbar {children: [prompt];}' \
        -theme-str '#inputbar {padding: 0.4em;}' \
        -theme-str '#listview {padding: 14 7 7 7;}' \
        -theme-str '#element {text-color: @blue;}' \
        -theme-str '#element.selected {background-color: @fore;}' \
        -theme-str '#element.selected {text-color: @back;}' \
        -theme-str '#window {x-offset: 42.3%; y-offset: -30.8%;}' \
        -theme-str '#window {width: 200;}'

