#! /bin/sh

export TERM=xterm

ARTIST=$(mocp -i | grep "Artist:" | sed -e "s/^.*: //")
SONGTITLE=$(mocp -i | grep "SongTitle:" | sed -e "s/^.*: //")
ALBUM=$(mocp -i | grep "Album:" | sed -e "s/^.*: //")

(echo -e "Interpret: $ARTIST"
echo -e "Pieseň: $SONGTITLE"
echo -e "Album: $ALBUM"
) | rofi -markup-rows -hide-scrollbar -no-fullscreen -no-custom -lines 3 \
	-font 'Terminus bold 12' \
	-theme "$HOME/.config/rofi/themes/green-grey-blue-theme.rasi" \
        -theme-str '#inputbar {children: [prompt];}' \
        -theme-str '#inputbar {padding: 0.4em;}' \
        -theme-str '#listview {padding: 14 7 7 7;}' \
        -theme-str '#window {x-offset: 10%; y-offset: -37.2%;}' \
        -theme-str '#window {width: 400;}' \
        -theme-str '#window {padding: 0;}' \
        -theme-str '#element {padding: 6;}' \
        -theme-str '#element {text-color: @blue;}' \
        -theme-str '#element selected.normal {background-color: @back;}' \
	-dmenu -p '               P R Á V E   H R Á'
