#!/bin/bash

export TERM=xterm
USE_LOCKER='false'
LOCKER='i3lock-my'

OPT=$(echo -e 'Cancel\nLock\nLogout\nReboot\nPoweroff' \
	| rofi -markup-rows -hide-scrollbar -no-fullscreen -no-custom \
    	-location 0 -bw 2 -eh 1 \
	-font 'Terminus bold 13' \
	-theme "$HOME/.config/rofi/themes/green-grey-blue-theme.rasi" \
        -theme-str '#inputbar {enabled: false;}' \
        -theme-str '#inputbar {children: [prompt];}' \
        -theme-str '#inputbar {padding: 0px;}' \
        -theme-str '#window {x-offset: 0%; y-offset: -41%;}' \
        -theme-str '#window {width: 530;}' \
        -theme-str '#listview {padding: 8px;}' \
        -theme-str '#listview {columns: 5;}' \
        -theme-str '#listview {lines: 1;}' \
        -theme-str '#element {horizontal-align: 0.55;}' \
        -theme-str '#element {text-color: @blue;}' \
        -theme-str '#element.selected {background-color: @blue;}' \
        -theme-str '#element.selected {text-color: @back;}' \
	-dmenu -i -p '                    Powermenu')

if [ ${#OPT} -gt 0 ]
then
    case $OPT in
	Cancel) ;;
	Lock) i3lock-my ;;
	Logout) i3-msg exit ;;
      	Reboot) systemctl reboot ;;
      	Poweroff) systemctl poweroff ;;
      	Suspend) $($USE_LOCKER) && "$LOCKER"; systemctl suspend ;;
      	Hibernate) $($USE_LOCKER) && "$LOCKER"; systemctl hibernate ;;
      	*) ;;
    esac
fi

