#!/bin/zsh
# A fuzzy file-finder and opener based on rofi 
# Requires: rofi, xdg-utils, ttf-ionicons 

files=$(find -type d -not -path '*/\.*' 2> /dev/null | sed -e 's/^\./ ~/g'
find -not -type d 2> /dev/null \
	| sed -E -e '/png$|jpg$|tiff$|gif$|jpeg$|bmp$/ s/^\./ ~/g' \
	| sed -E -e '/mp3$|flac$|pcm$|wav$|aac$|ogg$|wma$/ s/^\./ ~/g' \
	| sed -E -e '/wmv$|webm$|m4v$|mkv$|mov$|flv$|avi$|mp4$/ s/^\./ ~/g' \
	| sed -E -e 's/^/ /g')

input=$(echo $files \
	| rofi -markup-rows -no-fullscreen -hide-scrollbar \
        	-theme-str '#inputbar {children: [prompt,entry];}' \
        	-theme-str '#entry {padding: 8px;}' \
		-theme-str '#window {x-offset: 0%; y-offset: -2%;}' \
    		-theme-str '#window {width: 900;}' \
		-lines 20 -dmenu -p ) 
	case "$(echo $input | cut -d " " -f 1)" in
		a) exec $BROWSER https://wiki.archlinux.org/index.php/"$(echo $input | cut -d " " -f2-)" &> /dev/null & ;;
		w) exec $BROWSER https://en.wikipedia.org/wiki/"$(echo $input | cut -d " " -f2-)" &> /dev/null & ;;
		s) exec $BROWSER "https://www.google.sk/search?q=$(echo $input | cut -d " " -f2-)" &> /dev/null & ;;
		*) exec xdg-open "$(echo $input | sed 's/^....//g')" &> /dev/null & ;;
	esac
