#!/bin/bash

SCONTROL="${BLOCK_INSTANCE:-$(amixer -c 0 get Master | grep "Mono:" | awk '{print $4}' | tr -d "[ %]")}"
STEP="${1:-5%}"

volume() {
  amixer -D pulse get $SCONTROL
}

format() {
  perl_filter='if (/.*\[(\d+%)\] (\[(-?\d+.\d+dB)\] )?\[(on|off)\]/)'
  perl_filter+='{CORE::say $4 eq "off" ? "stlmený  " : "'
  perl_filter+=$([[ $STEP = *dB ]] && echo '$3  ' || echo '$1  ')
  perl_filter+='"; exit}'
  perl -ne "$perl_filter"
}

case $BLOCK_BUTTON in
  1) amixer -q -D pulse sset $SCONTROL toggle ;;  # left click, mute/unmute
#  2) $HOME/.config/i3/Scripts/mocp_rofi ;; # middle click
  4) amixer -q -D pulse sset $SCONTROL ${STEP}+ unmute ;; # scroll up, increase
  5) amixer -q -D pulse sset $SCONTROL ${STEP}- unmute ;; # scroll down, decrease
esac

volume | format
