#!/bin/bash

governor=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
policy="Permission needed to change CPU governor. Please enter password..."

if [ "$governor" == "powersave" ]; then
    xterm -title "Governor" -class UXTerm -e "echo $policy && echo performance | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor && notify-send 'CPU Performance Enabled'"
else
    xterm -title "Governor" -class UXTerm -e "echo $policy && echo powersave | sudo tee /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor && notify-send 'CPU Powersave Enabled'"
fi
exit 0
cpupower frequency-info
cpupower frequency-info | sed -n '14,15 p'
