#!/bin/bash
export DISPLAY=:0.0
export XAUTHORITY=/home/${USER}/.Xauthority


if ! packages=$(checkupdates 2> /dev/null  | cut -d " " -f1 | wc -l); then
    packages=0
fi

if ! AUR=$(pikaur -Qua 2> /dev/null | wc -l); then
    AUR=0
fi

#notify-send --urgency=critical "Aktualizácia systému: $packages
#Aktualizácia AUR: $AUR"

notify-send --urgency=critical "  " "$(echo -en "Aktualizácia systému: $packages\nAktualizácia AUR: $AUR")"
