#!/bin/bash

governor=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
temp=$(sensors 'coretemp-*' | grep '^Package id' | awk '{print $4}' | grep -o '[0-9]\+'  | head -n1)
fore="#c0c5ce"


if [[ $governor == powersave ]]; then
	governors+=("?")
else
	governors+=("!")
fi

if [[ $temp -lt 60 ]]; then
	temps+=("-")
elif [[ $temp -ge 80 ]]; then
	temps+=("!")
else 
	temps+=("+")
fi

case $BLOCK_BUTTON in
	1) $HOME/.config/i3/Scripts/cpu_governor ;;
esac

#message="$message ${governors[i]}${temps[i]}"
message="$message <span foreground=\"$fore\">${governors[i]}${temps[i]}</span>"

echo $message
