#!/bin/bash 

VOL=$(amixer -c 0 get Master | grep "Mono:" | awk '{print $4}' | tr -d "[ %]")
MUTE=$(amixer -c 0 get Master | grep "Mono:" | awk '{print $6}' | tr -d "[-]")

if [ "$MUTE" = "off" ];then 
    icon0=""
else
    icon0=""
    icon1=""
    icon2=""
    icon3=""
    icon4=""
fi

if [ "$MUTE" = "off" ];then 
    echo -e "$icon0 stlmený"
else
    if [ "$VOL" -gt "80" ];then
        echo -e "$icon4 $VOL%"
    elif [ "$VOL" -gt "60" ];then
        echo -e "$icon3 $VOL%"
    elif [ "$VOL" -gt "40" ];then
        echo -e "$icon2 $VOL%"
    elif [ "$VOL" -gt "20" ];then
        echo -e "$icon1 $VOL%"
    elif [ "$VOL" -eq "0" ];then 
        echo -e "$icon0 $VOL%"
    fi 
fi 
 
case $BLOCK_BUTTON in
  1) amixer -q set Master toggle ;;  # left click, mute/unmute
  2) $HOME/.config/i3/Scripts/mocp_rofi ;; # middle click
  4) amixer -q set Master 5%+ unmute ;; # scroll up, increase
  5) amixer -q set Master 5%- unmute ;; # scroll down, decrease
esac

unset VOL
unset MUTE
