#!/bin/sh

FG='#5994ad'
BG='#303d44'
FGS='#303d44'
BGS='#5994ad'
FN='Terminus-14:bold'

$HOME/.config/i3/Scripts/scripts/dmenu_history -i -p "Search >>" \
	-h 28 -w 1200 -x 80 -y 50 \
	-fn $FN \
	-nb $BG -nf $FG -sb $BGS -sf $FGS
