#!/bin/bash

STATUS=$(mocp -i | grep "State:" | sed -e "s/^.*: //")
TITLE=$(mocp -i | grep "^Title:" | sed -e "s/^.*: //")
ARTIST=$(mocp -i | grep "Artist:" | sed -e "s/^.*: //")
SONGTITLE=$(mocp -i | grep "SongTitle:" | sed -e "s/^.*: //")
MAX=40
LENGHT="$(echo "$SONGTITLE" | wc -c)"
offset="$MAX"
let offset=offset-3

if [[ "$LENGHT" -gt "$MAX" ]]; then
  SONGTITLE_SHORT="$(echo $SONGTITLE | cut -b 1-${offset})..."
  SONGTITLE="${SONGTITLE_SHORT}"
fi

if [[ $STATUS == PLAY ]]; then
  if [[ $TITLE != "" ]]; then
    if [[ $ARTIST != "" ]]; then ARTIST="$ARTIST -"; fi
      echo -e " $ARTIST $SONGTITLE"
    else echo -e " Prehráva sa"
   fi
fi

#if [[ $STATUS == PAUSE ]]; then
#      echo -e "    Pozastavené"
#fi

if [[ $STATUS == PAUSE ]]; then
  if [[ $TITLE != "" ]]; then
    if [[ $ARTIST != "" ]]; then ARTIST="$ARTIST -"; fi
      echo -e "  $ARTIST $SONGTITLE"
    else echo -e "  Pozastavené"
   fi
fi

if [ $? -eq 0 ]; then
    echo -e " Stopnuté"
fi

case $BLOCK_BUTTON in
    1) mocp -G ;;
    2) mocp -r ;;
    3) mocp -f ;;
esac
exit 0

if [[ ! -z $(pidof mocp) ]] &>/dev/null 2>&1; then
  echo -e " "
else echo -e " "
fi

