#!/bin/bash

export TERM=xterm
rofi -modi window,windowcd,run,drun,ssh,calc -show run -sidebar-mode -lines 13 \
	-markup-rows -hide-scrollbar -no-fullscreen -no-custom -no-lazy-grab \
	-location 0 -bw 2 -eh 1 \
        -theme-str '#window {width: 600;}' \
        -theme-str '#window {x-offset: -3%; y-offset: -13%;}'
