#!/bin/bash

export TERM=xterm
USE_LOCKER='false'
LOCKER='i3lock-my'

OPT=$(echo -e '✘  Cancel\n  Desktop\n  Window\n  Sector\n  Flameshot\n  Desktops' \
	| rofi -markup-rows -hide-scrollbar -no-fullscreen -no-custom -no-lazy-grab \
    	-location 0 -bw 2 -eh 1 \
	-theme "$HOME/.config/polybar/themes/green-grey-blue-theme.rasi" \
        -theme-str '#window {x-offset: 0%; y-offset: -35%;}' \
        -theme-str '#window {width: 195;}' \
	-theme-str '#window {border: 4px;}' \
        -theme-str '#window {border-color: @back;}' \
        -theme-str '#wrapper-mode-switcher {enabled: false;}' \
        -theme-str '#inputbar {enabled: false;}' \
        -theme-str '#inputbar {children: [prompt];}' \
        -theme-str '#inputbar {padding: 0px;}' \
        -theme-str '#listview {padding: 10;}' \
        -theme-str '#listview {columns: 1;}' \
        -theme-str '#listview {lines: 6;}' \
        -theme-str '#listview {border: 3px;}' \
        -theme-str '#listview {border-color: @text;}' \
	-theme-str '#element {padding: 5 0 5 0;}' \
        -theme-str '#element.selected {text-color: @white;}' \
	-dmenu -i -p '                    Screenshots')

if [ ${#OPT} -gt 0 ]
then
    case $OPT in
	*Cancel) ;;
	*) scrot -d 5 -q 100 ~/Obrázky/snímka_%Y-%m-%d_%H-%M-%S.png; exec notify-send 'Snímka plochy vytvorená' ;;
	*) scrot -d 1 -u -q 100 ~/Obrázky/snímka_%Y-%m-%d_%H-%M-%S.png; exec notify-send 'Snímka okna vytvorená' ;;
      	*) scrott -d 1 -s -e -q 100 ~/Obrázky/snímka_%Y-%m-%d_%H-%M-%S.png; exec notify-send 'Snímka výseku vytvorená' ;;
      	*) flameshot gui ;;
      	*) mate-screenshot --interactive ;;
      	*) $HOME/.config/polybar/scripts/screenie; exec notify-send 'Snímka plôch vytvorená' ;;
      	*) ;;
    esac
fi
