#!/bin/bash

green="\[$(tput setaf 2)\]"
bold="\[$(tput bold)\]"

pikaur --noconfirm -Syyu
echo ""
echo ""
read -n 1 -r -s -p $(tput setaf 2;tput bold)'Pre pokračovanie stisni akúkoľvek klávesu... '












