#!/bin/bash

export TERM=xterm
USE_LOCKER='false'
LOCKER='i3lock-my'

OPT=$(echo -e '✘  Cancel\n  Lock\n  Logout\n  Reboot\n  Poweroff' \
	| rofi -markup-rows -hide-scrollbar -no-fullscreen -no-custom -no-lazy-grab \
    	-location 0 -bw 2 -eh 1 \
	-theme "$HOME/.config/polybar/themes/green-grey-paper-float-menu.rasi" \
        -theme-str '#window {x-offset: 0%; y-offset: -36%;}' \
        -theme-str '#window {width: 207;}' \
        -theme-str '#window {border-color: @back;}' \
        -theme-str '#mode-switcher {enabled: false;}' \
        -theme-str '#inputbar {enabled: false;}' \
        -theme-str '#listview {padding: 20 10 10 20;}' \
        -theme-str '#listview {lines: 5;}' \
	-dmenu -i -p 'Powermenu')

if [ ${#OPT} -gt 0 ]
then
    case $OPT in
	*Cancel) ;;
	*Lock) i3lock-my ;;
	*Logout) i3-msg exit ;;
      	*Reboot) reboot ;;
      	*Poweroff) poweroff ;;
      	*Suspend) $($USE_LOCKER) && "$LOCKER"; suspend ;;
      	*Hibernate) $($USE_LOCKER) && "$LOCKER"; hibernate ;;
      	*) ;;
    esac
fi

