#!/bin/bash

export TERM=xterm

OPT=$(echo -e '\n\n\n\n\n' \
	| rofi -markup-rows -hide-scrollbar -no-fullscreen -no-custom -no-lazy-grab \
    	-location 0 -bw 2 -eh 1 \
	-theme "$HOME/.config/rofi/themes/powermenu-fullscreen.rasi" \
	-theme-str '#window {width: 90%;}' \
	-theme-str '#window {height: 19%;}' \
        -theme-str '#window {x-offset: 0%; y-offset: -10%;}' \
        -theme-str '#window {border-color: @back;}' \
        -theme-str '#wrapper-mode-switcher {enabled: false;}' \
        -theme-str '#inputbar {enabled: false;}' \
        -theme-str '#inputbar {children: [prompt];}' \
        -theme-str '#inputbar {padding: 0px;}' \
        -theme-str '#listview {padding: 10;}' \
        -theme-str '#listview {columns: 1;}' \
        -theme-str '#listview {lines: 6;}' \
        -theme-str '#listview {border: 0px;}' \
        -theme-str '#listview {border-color: @text;}' \
        -theme-str '#listview {layout: horizontal;}' \
        -theme-str '#element {horizontal-align: 0.50;}' \
	-theme-str '#element {padding: 5 0 5 0;}' \
        -theme-str '#element {text-color: @text-alt;}' \
        -theme-str '#element.selected {background-color: @back;}' \
        -theme-str '#element.selected {text-color: @text;}' \
	-dmenu -i -p '  Screenshot Menu  ')

if [ ${#OPT} -gt 0 ]
then
    case $OPT in
	*) scrot -d 5 -q 100 ~/Obrázky/snímka_%Y-%m-%d_%H-%M-%S.png; exec notify-send 'Snímka plochy vytvorená' ;;
	*) scrot -d 1 -u -q 100 ~/Obrázky/snímka_%Y-%m-%d_%H-%M-%S.png; exec notify-send 'Snímka okna vytvorená' ;;
      	*) scrott -d 1 -s -e -q 100 ~/Obrázky/snímka_%Y-%m-%d_%H-%M-%S.png; exec notify-send 'Snímka výseku vytvorená' ;;
      	*) flameshot gui ;;
      	*) mate-screenshot --interactive ;;
      	*) $HOME/.config/polybar/scripts/screenie; exec notify-send 'Snímka plôch vytvorená' ;;
      	*) ;;
    esac
fi

