#!/bin/sh
tmppng=/tmp/i3scrots

if [[ $(command -v scrot) = "" ]] || [[ $(command -v convert) = "" ]]; then
        echo "Script needs scrot, and imagemagick's 'convert'"
        echo "Aborting" ; exit 1
fi

[[ ! -d $tmppng ]] && mkdir $tmppng
count=$(i3-msg -t get_workspaces | grep -Eo visible | wc -w)

eet() {
        scrot -d 1 -c -m -q 100 $tmppng/$n.png && i3-msg workspace next
}

n=0; while [[ $n -lt $count ]]; do eet 1>/dev/null; n=$(($n+1)); done

echo "appending to $HOME/Obrázky/plochy.png"
convert $tmppng/*.png +append $HOME/Obrázky/plochy.png
rm $tmppng -rf
#echo "uploading to ptpb.pw"
#pbpst -Sf $HOME/Obrázky/plochy.png
