#!/bin/bash


export LC_ALL=C
export LANG=C

#OS=$(hostnamectl | awk 'NR==6{print $3,$4}')
OS=$(awk -F'=' 'gsub("release", "Linux", $1)' /etc/artix-release)
KERNEL=$(uname -r)
ARCH=$(uname -m)
UPTIME=$(uptime -p | sed -e "s/up //")
MODEL=$(cat  /sys/devices/virtual/dmi/id/product_name)
DE=$(ps -A | awk '/i3/{print $4}' | head -1)
CPU=$(lscpu | awk '/Model name:/{gsub(/[(TMR)]/,"");print $3,$4,$5,$6,$7,$8,$9}' | head -1)
GPU=$(lspci | awk '/VGA/{print $5,$8,$9,$10}' | tr -d '[]')
SHELL=$(zsh --version  | awk '{print $1,$2}')
RESOLUTION=$(xdpyinfo | awk '/dimensions:/{print $2}')

BIRTH=$(ls -dlct "/lost+found" | awk '{print $7,$6}')
BIRTH_DATE=$(date -d "$BIRTH" "+%a")
BIRTH_YEAR=$(cat /var/log/pacman.log | awk 'NR==1{print $1}' | cut -c 2-5)
BIRTH_TIME=$(ls -dlct "/lost+found" | awk '{print $8}')

gtkrc="$HOME/.gtkrc-2.0"
GtkTheme=$( grep "gtk-theme-name" "$gtkrc" | cut -d\" -f2 )
GtkIcon=$( grep "gtk-icon-theme-name" "$gtkrc" | cut -d\" -f2 )
GtkFont=$( grep "gtk-font-name" "$gtkrc" | cut -d\" -f2 )

Artist=$(mocp -i | grep "Artist:" | sed -e "s/^.*: //")
SongTitle=$(mocp -i | grep "SongTitle:" | sed -e "s/^.*: //")
Album=$(mocp -i | grep "Album:" | sed -e "s/^.*: //")



 echo  ""
 echo -e "\e[94m   -------------------"
 echo "   SYSTEM INFORMATIONS"
 echo "   -------------------"
 echo  ""
 echo -e "\e[94m     lombardo1981"
 echo -e "\e[94m     \e[39m$MODEL"
 echo -e "\e[94m     \e[39m$OS $ARCH"
 echo -e "\e[94m     \e[39m$KERNEL"
 echo -e "\e[94m     \e[39m$UPTIME"
 echo -e "\e[94m     \e[39m$SHELL"
 echo -e "\e[94m     \e[39m$RESOLUTION"
 echo -e "\e[94m     \e[39m$CPU"
 echo -e "\e[94m     \e[39m$GPU"
 echo -e "\e[92m   -------------------"
 echo -e "\e[92m     \e[92m$DE"
 echo -e "\e[92m     \e[39m$GtkTheme"
 echo -e "\e[92m     \e[39m$GtkIcon"
 echo -e "\e[92m     \e[39m$GtkFont"
 echo -e "\e[92m     \e[39m$BIRTH_DATE $BIRTH $BIRTH_YEAR $BIRTH_TIME"
 echo -e "\e[91m   -------------------"
 echo -e "\e[91m     $Artist"
 echo -e "\e[91m     $SongTitle"
 echo -e "\e[91m     $Album"
 echo  ""
