#!/bin/bash

export TERM=xterm
USE_LOCKER='false'
LOCKER='i3lock-my'
FIREFOX='firefox-sync'
UPTIME="`uptime -p | sed -e 's/up //g'`"
HOST=`hostname`

#OPT=$(echo -e '✘  Cancel\n  Lock\n Logout\n  Reboot\n  Poweroff' \
OPT=$(echo -e '✘\n \n\n\n' \
	| rofi -markup-rows -hide-scrollbar -no-fullscreen -no-custom -no-lazy-grab \
    	-location 0 -bw 2 -eh 1 \
	-theme "$HOME/.config/polybar/themes/nordic-paper-float-powermenu.rasi" \
        -theme-str '#window {x-offset: 0%; y-offset: -16%;}' \
        -theme-str '#window {width: 500;}' \
        -theme-str '#entry {enabled: false;}' \
        -theme-str '#inputbar {enabled: false;}' \
        -theme-str '#listview {lines: 1;}' \
	-theme-str '#listview {columns: 5;}' \
	-dmenu -i -p "  $HOST")
#	-mesg " $UPTIME")
#      -theme-str '#window {width: 440;}' \
        
if [ ${#OPT} -gt 0 ]
then
    case $OPT in
	*✘) ;;
	*) i3lock-my ;;
	*) i3-msg exit ;;
      	*) systemctl reboot ;;
      	*) systemctl poweroff ;;
      	*Suspend) $($USE_LOCKER) && "$LOCKER"; suspend ;;
      	*Hibernate) $($USE_LOCKER) && "$LOCKER"; hibernate ;;
      	*) ;;
    esac
fi

