#!/bin/bash

export TERM=xterm

OPT=$(echo -e '✘  Cancel\n  Desktop\n  Window\n  Sector\n  Flameshot\n  Selection\n  Desktops' \
	| rofi -markup-rows -hide-scrollbar -no-fullscreen -no-custom -no-lazy-grab \
    	-location 0 -bw 2 -eh 1 \
	-theme "$HOME/.config/polybar/themes/nordic-paper-float-menu.rasi" \
        -theme-str '#window {x-offset: 0%; y-offset: -32%;}' \
        -theme-str '#window {width: 207;}' \
        -theme-str '#window {border-color: @back;}' \
        -theme-str '#mode-switcher {enabled: false;}' \
        -theme-str '#inputbar {enabled: false;}' \
        -theme-str '#listview {padding: 20 10 10 20;}' \
        -theme-str '#listview {lines: 7;}' \
	-dmenu -i -p 'Screenshot Menu')

if [ ${#OPT} -gt 0 ]
then
    case $OPT in
	*Cancel) ;;
	*Desktop) scrot -d 5 -q 100 ~/Obrázky/snímka_%Y-%m-%d_%H-%M-%S.png; exec notify-send 'Snímka plochy vytvorená' ;;
	*Window) scrot -d 1 -u -q 100 ~/Obrázky/snímka_%Y-%m-%d_%H-%M-%S.png; exec notify-send 'Snímka okna vytvorená' ;;
      	*Sector) scrott -d 1 -s -e -q 100 ~/Obrázky/snímka_%Y-%m-%d_%H-%M-%S.png; exec notify-send 'Snímka výseku vytvorená' ;;
      	*Flameshot) flameshot gui ;;
      	*Selection) mate-screenshot --interactive ;;
      	*Desktops) $HOME/.config/polybar/scripts/screenie; exec notify-send 'Snímka plôch vytvorená' ;;
      	*) ;;
    esac
fi

