#!/bin/bash


export LC_ALL=C
export LANG=C

OS=$(hostnamectl | awk 'NR==6{print $3,$4}')
#OS=$(awk -F'=' 'gsub("release", "", $1)' /etc/artix-release)
KERNEL=$(uname -r)
ARCH=$(uname -m)
UPTIME=$(uptime -p | sed -e "s/up //")
VENDOR=$(cat  /sys/devices/virtual/dmi/id/board_vendor)
MODEL=$(cat  /sys/devices/virtual/dmi/id/product_name)
BIOS=$(cat  /sys/devices/virtual/dmi/id/bios_vendor)
DE=$(ps -A | awk '/i3/{print $4}' | head -1)
CPU=$(lscpu | awk '/Model name:/{gsub(/[(TMR)]/,"");print $3,$4,$5,$6,$7,$8,$9}' | head -1)
CPUs=$(lscpu | grep 'CPU(s)' | awk '{print $2}' | head -1)
GPU=$(lspci | awk '/VGA/{print $5,$8,$9,$10}' | tr -d '[]')
SHELL=$(zsh --version  | awk '{print $1,$2}')

#BIRTH=$(ls -dlct "/lost+found" | awk '{print $7,$6}')
#BIRTH_DATE=$(date -d "$BIRTH" "+%a")
#BIRTH_YEAR=$(cat /var/log/pacman.log | awk 'NR==1{print $1}' | cut -c 2-5)
BIRTH_DATE=$(cat /var/log/pacman.log | awk 'NR==1{print $1}' | cut -c 2-11)
#BIRTH_TIME=$(ls -dlct "/lost+found" | awk '{print $8}')
BIRTH_TIME=$(cat /var/log/pacman.log | awk 'NR==1{print $1}' | cut -c 13-20)

ram_used=$(free -m | awk '/Mem/{print $3" MB"}')
ram_total=$(free -m | awk '/Mem/{print $2" MB"}')
ram_per=$(free -m | awk 'NR==2{printf "%0.0f\n",$3/$2*100}')
cpu_user=$(mpstat | awk '/all/{print $3"%"}')
cpu_sys=$(mpstat | awk '/all/{print $5"%"}')
cpu_idle=$(mpstat | awk '/all/{print $12"%"}')
temp=$(sensors coretemp-isa-0000 | awk '/Package/{gsub(/+/, "");print $4}')
temp1=$(sensors coretemp-isa-0000 | awk '/Core 0/{gsub(/+/, "");print $3}')
temp2=$(sensors coretemp-isa-0000 | awk '/Core 1/{gsub(/+/, "");print $3}')
PACKAGES=$(pacman -Q | cut -d " " -f1 | wc -l)
MONITOR=$(cat /var/log/Xorg.0.log | awk 'NR==117{print $5,$6,$7}')
RESOLUTION=$(xdpyinfo | awk '/dimensions:/{print $2}')
LAYOUT=$(setxkbmap -query | awk '/layout/{print $2}')
LAYOUT2=$(setxkbmap -query | awk '/model/{print $2}' | tr -d ' ')

DISK1=$(df -h / | awk 'NR==2{total=$2;used=$3;print used" / "total}')
DISK2=$(df -h /home | awk 'NR==2{total=$2;used=$3;print used" / "total}')
DISK3=$(df -h / | awk 'NR==2{print $5}')
DISK4=$(df -h /home | awk 'NR==2{print $5}')
TRASH=$(ls -A -U -1 "${HOME}/.local/share/Trash/files" | cut -d " " -f1 | wc -l)

gtkrc="$HOME/.gtkrc-2.0"
GtkTheme=$(grep "gtk-theme-name" "$gtkrc" | cut -d\" -f2)
GtkIcon=$(grep "gtk-icon-theme-name" "$gtkrc" | cut -d\" -f2)
GtkFont=$(grep "gtk-font-name" "$gtkrc" | cut -d\" -f2)
termfn=$(cat $HOME/.config/termite/config | awk 'NR==10' | grep 'font' | sed 's/font = //')

Artist=$(mocp -i | grep "Artist:" | sed -e "s/^.*: //")
SongTitle=$(mocp -i | grep "SongTitle:" | sed -e "s/^.*: //")
Album=$(mocp -i | grep "Album:" | sed -e "s/^.*: //")



 echo  ""
 echo -e "\e[94m   -------------------"
 echo "   SYSTEM INFORMATIONS"
 echo "   -------------------"
 echo  ""
 echo -e "\e[94m     lombardo1981"
 echo -e "\e[94m     \e[39m$OS $ARCH"
 echo -e "\e[94m     \e[39m$KERNEL"
 echo -e "\e[94m     \e[39m$UPTIME"
 echo -e "\e[94m     \e[39m$SHELL"
 echo -e "\e[94m     \e[39m$BIRTH_DATE $BIRTH_TIME"
 echo -e "\e[94m     \e[39m$PACKAGES"
 echo -e "\e[36m   -------------------"
 echo -e "\e[36m     \e[36m$VENDOR $MODEL"
 echo -e "\e[36m     \e[39m$BIOS"
 echo -e "\e[36m     \e[39m$CPU"
 echo -e "\e[36m     \e[39m$CPUs"
 echo -e "\e[36m     \e[39m$GPU"
 echo -e "\e[36m     \e[39m$MONITOR"
 echo -e "\e[36m     \e[39m$RESOLUTION"
 echo -e "\e[36m     \e[39mNiceboy ORYX K300X"
 echo -e "\e[36m     \e[39m$LAYOUT ($LAYOUT2)"
 echo -e "\e[36m     \e[39mAQ Galaxy Scorpio GGM01SC"
 echo -e "\e[95m   -------------------"
 echo -e "\e[95m     \e[39m$ram_used / $ram_total \e[95m($ram_per%)"
 echo -e "\e[95m     \e[39m$cpu_user / $cpu_sys / $cpu_idle"
 echo -e "\e[95m     \e[39m$temp / $temp1 / $temp2"
 echo -e "\e[95m     \e[39m$DISK1 \e[95m($DISK3)"
 echo -e "\e[95m     \e[39m$DISK2 \e[95m($DISK4)"
 echo -e "\e[95m     \e[39m$TRASH"
 echo -e "\e[92m   -------------------"
 echo -e "\e[92m     \e[92m$DE"
 echo -e "\e[92m     \e[39m$GtkTheme"
 echo -e "\e[92m     \e[39m$GtkIcon"
 echo -e "\e[92m     \e[39m$GtkFont"
 echo -e "\e[92m     \e[39m$termfn"
 echo -e "\e[91m   -------------------"
 echo -e "\e[91m     $Artist"
 echo -e "\e[91m     $SongTitle"
 echo -e "\e[91m     $Album"
 echo  ""
